# Generated by Django 6.1.1 on 2026-10-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="familymember",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
