# Generated by Django 6.1.1 on 2026-10-04 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0003_doctor_medicaldocument_medicalhistory_vitalrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_name", models.CharField(max_length=150)),
                ("renewal_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "family_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_claims",
                        to="family.familymember",
                    ),
                ),
            ],
        ),
    ]
