# Generated by Django 6.1.1 on 2026-10-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="afternoon",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="food_timing",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="morning",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="night",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="stock",
        ),
        migrations.AddField(
            model_name="medicine",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="dosage",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="DoseLog",
        ),
    ]
