# Generated by Django 6.1.1 on 2026-10-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0002_remove_medicine_afternoon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("dosage", models.CharField(max_length=100)),
                (
                    "meal_relation",
                    models.CharField(
                        choices=[
                            ("before_food", "Before Food"),
                            ("after_food", "After Food"),
                            ("with_food", "With Food"),
                            ("anytime", "Anytime"),
                        ],
                        default="anytime",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="medicines.medicine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="medicines.medicineschedule",
                    ),
                ),
            ],
        ),
    ]
